### ISSUE TITLE
Device not found - multicast-dns related issue

### ISSUE THREAD

**Issue by simonbcn** [Rafostar/gnome-shell-extension-cast-to-tv#64]
```
Arch Linux
gnome-shell-extension-cast-to-tv v9 (installed from https://extensions.gnome.org/extension/1544/cast-to-tv)
GNOME Shell 3.32.2
```
I have a Sony AG9 with Chromecast integrated (_it uses Android TV_).
I installed the application and it worked the first time but after that it doesn't work anymore nor detect the chromecast device.
It only shows the error "_Device not found_".

**Comment by Rafostar** [comment]
If it worked earlier, I assume your firewall is not blocking. Device detection sometimes fails depending on used **router** and **network card** that your PC has.

As a workaround, try installing [cast-to-tv-config](https://github.com/Rafostar/cast-to-tv-config), check your current Chromecast device IP address using *Google Home* app and manually set it using this terminal tool, then select device you just added in extension settings (Device selection in Chromecast tab).

**Comment by simonbcn** [comment]
With _cast-to-tv-config_ it works. Thanks.

**Comment by Rafostar** [comment]
No problem. I made that terminal app, because I had similar problems on one of my laptops (it really depends on router and wifi card). In the future I will try to integrate the manual setting of IP in extension preferences, but making GUI is a lot more time consuming then a simple terminal app, so I made it as a temporary workaround.

Please remember to assign your TV a static IP address, otherwise you will not be able to connect when IP changes (without running config again).

**Comment by simonbcn** [comment]
The TV Sony AG9 uses Android TV v8 and is connected to LAN via wifi.

`avahi` detects this device:
```
$ avahi-discover 
....
Browsing for services of type '_googlecast._tcp' in domain 'local' on 2.0 ...
....
Found service 'BRAVIA-4K-UR2-c09f0efe70e5192e34da32e146cec348' of type '_googlecast._tcp' in domain 'local' on 2.0.
```
But `gnome-shell-extension-cast-to-tv` doesn't detect it.

**Comment by Rafostar** [comment]
Ok, but since you reopened this, please tell me if manual IP config through [cast-to-tv-config](https://github.com/Rafostar/cast-to-tv-config) made it work each time. I need to know if it is only scan or connection related.

**Comment by simonbcn** [comment]
I've reopened the issue because it isn't a problem of connection (avahi see the service: https://developers.google.com/cast/docs/discovery ). With manual IP config it works.

**Comment by Rafostar** [comment]
This extension uses `multicast-dns` node module to do the scanning and obtain IP. I am not the creator of it, but since I have similar problems on one of my devices I will look into it to find the reason and maybe send them a PR if I manage to find the cause. Until then please use the config tool to set IP. It skips network scan entirely and makes the connection establishment faster too.

So, eventual improvement (if I find anything) might appear in v11 later this year (probably some time after Gnome 3.34 release). I also have to deal with mix of peaple using v9 and v10, since that later one is stuck on Gnome Shell Extensions website review queue for almost a month now :disappointed:

**Comment by simonbcn** [comment]
Is this the `mulsticast-dns` module used: https://www.npmjs.com/package/multicast-dns ?
In which part of code is this search of Chromecast devices?

**Comment by Rafostar** [comment]
Yes, that one. The scan code is in [multicast-scanner](https://www.npmjs.com/package/multicast-scanner), which does nothing more than running `multicast-dns` with correct params for Chromecast(s) scanning and returns a result.

**Comment by simonbcn** [comment]
More info: https://github.com/Rafostar/multicast-scanner/issues/1

**Comment by simonbcn** [comment]
Now that Rafostar/multicast-scanner#1 is fixed I've tried to change the version of `multicast-dns` and `multicast-scanner` in the extension `gnome-shell-extension-cast-to-tv` to test it but: 

- In `package.json` says `"multicast-scanner": "^2.0.1",` 

- In `package-lock.json` says `"multicast-scanner": "^2.0.0",` but below (_in same file_)
  ```
  ...
   "multicast-scanner": {
         "version": "2.0.1",
  ...
  ```
 - By other side, another dependency is `chromecast-player-reloaded` and its `package.json`uses `"multicast-scanner": "^2.0.0",`

I don't know how these files works on node but there are several inconsistencies. I think it would be necessary to arrange this mess of versions in all dependencies.

**Comment by Rafostar** [comment]
`multicast-scanner` in extension `package.json` is used in extension settings (preferences) to scan and refresh Chromecast(s) list in there.

`multicast-scanner` in `chromecast-player-reloaded` is used to find and connect to desired Chromecast.

> I don't know how these files works on node but there are several inconsistencies. I think it would be necessary to arrange this mess of versions in all dependencies.

Yes, I have to update EVERYTHING that uses `multicast-scanner`. But `chromecast-player-reloaded` has some other pending changes in git master that I need to test properly before releasing new version.

As a temporary solution for now, please download and replace `index.js` file from latest `multicast-scanner` to
```
~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/multicast-scanner
```
Changes should be applied on next extension service start (if you have updated to v10 turn it off from top bar menu and back on).

Please leave this one issue open, so I won't forget to update it :smile:

**Comment by Rafostar** [comment]
No, wait. Ignore the above. This would not replace `multicast-dns` and we cannot replace it manually as it's dependencies have other versions too.

Better wait until I have time to test everything properly and replace those versions. Until then you still have a temporary solution for connecting by IP.

**Comment by Rafostar** [comment]
I updated git master today. It took longer than I anticipated because of other bugs I had to completely rework Chromecast devices controlling module from scratch. Beside the updated scanner, there are some new features that I mentioned [in this post](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv/issues/65#issuecomment-535862998).

Some changes in latest git code will make the `cast-to-tv-config` not work anymore. Please be warned.

I will do another release as soon as I finish making the GUI for manual config of IP (which you hopefully will not be forced to use anymore) inside extension settings and test everything properly.

**Comment by Rafostar** [comment]
Posted extension version 11 to GNOME extensions website. New version uses updated scanner as requested. Therefore I consider this issue solved. Closing.
