### ISSUE TITLE
"npm not installed", but 6.11.3 is installed

### ISSUE THREAD

**Issue by diego-betto** [Rafostar/gnome-shell-extension-cast-to-tv#79]
Hi, 

I've already installed node/nodejs and npm (I use them on daily basis since I'm web developer) but if I open the settings section it says that npm is not installed

**Comment by Rafostar** [comment]
Where is npm installed?

What is the terminal output of:
```
which npm
```

The extension uses a simple one-liner
```
GLib.find_program_in_path('npm');
```
to get the path to binary from user `Environment`. If this function does not find it, a `null` is returned and the message you see is displayed.

**Comment by Rafostar** [comment]
@diego-betto Did you verify npm install path as I described few days ago and manage to solve it? If yes I would like to close this issue and eventually add the possible workaround to the wiki if someone else faces similar problem.

**Comment by diego-betto** [comment]
Sorry man for my delay.

my npm location is 
`/home/user/.nvm/versions/node/v10.16.0/bin/npm`

and `/home/user/.nvm/versions/node/v10.16.0/bin` is included in $PATH

**Comment by Rafostar** [comment]
@diego-betto 
`/home/user/.nvm/versions/node/v10.16.0/bin/npm` is a really non-standard location. Probably GLib cannot access it.

Making a symbolic link should solve it:
```
sudo ln -s "/home/user/.nvm/versions/node/v10.16.0/bin/npm" /usr/bin/npm
```
Not sure if reboot will be required afterwards, through.

**Comment by diego-betto** [comment]
Awesome, it works. 

Maybe add to documentation since many developes uses `nvm` or similar tools to manage nodejs versions. 

Thanks a lot!

**Comment by airtonix** [comment]
> @diego-betto
> `/home/user/.nvm/versions/node/v10.16.0/bin/npm` is a really non-standard location. Probably GLib cannot access it.

what does "non standard" mean?

- https://developer.gnome.org/glibmm/stable/group__MiscUtils.html#gaa4c4ecb9a3eb803ae6d9dee51e1e5b14

```console
❯ echo $PATH
/home/zenobius/.nvm/versions/node/v12.19.0/bin:/home/zenobius/Applications:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/zenobius/bin

❯ which npm
~/.nvm/versions/node/v12.19.0/bin/npm

❯ nvm ls
->     v12.19.0
default -> 12.19.0 (-> v12.19.0)
node -> stable (-> v12.19.0) (default)
stable -> 12.19 (-> v12.19.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/fermium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.23.0 (-> N/A)
lts/erbium -> v12.19.0
lts/fermium -> v14.15.0 (-> N/A)

❯ npm -v
6.14.8

```

according to `glibmm` documentation above this should work.

**Comment by Rafostar** [comment]
@airtonix 
> what does "non standard" mean?

By this I meant that this path is not normally in the Linux $PATH by default. I might be wrong here cause I do not use `nvm` but I think that the reason that this does not work is because `nvm` is adding its own `npm` path after user login, while GNOME Shell loads earlier and uses the default $PATH before modifications done by `nvm`.

**Comment by brunodrugowick** [comment]
I also use `nvm` to handle `npm` versions and my scenario is exactly the same as the OP. I tried creating a symlink, then moved to a LTS version of node, recreated the symlink, logged out, restarted... still getting a `Nodejs is not installed` on the configuration screen.

Is there any other ting I could check to get to the root cause in my case?

**Comment by lyleaigbedion** [comment]
Having the same issue as well on Ubuntu 18.04. I use nvm as well and did all the steps outlined.

**Comment by Rafostar** [comment]
Usually to get this working is:

1. create symlinks from your `node` bin to `/usr/bin/node` and `npm` to `/usr/bin/npm`
2. check if they work by starting `/usr/bin/node` and `/usr/bin/npm` from terminal (with full symlink path)
3. reboot

I do not have a better workaround right now. This is the limitation caused by starting this as part of `gnome-shell` process. If this is still problematic, I will **try** to find some way to get this working without workarounds...

**Comment by lyleaigbedion** [comment]
Thank you, I made the mistake of not creating a symlink to node like I did with npm. It is working now though I'll need to upgrade Ubuntu to take advantage of the desktop casting. Thanks again!

**Comment by brunodrugowick** [comment]
> Usually to get this working is:
> 
>     1. create symlinks from your `node` bin to `/usr/bin/node` and `npm` to `/usr/bin/npm`
> 
>     2. check if they work by starting `/usr/bin/node` and `/usr/bin/npm` from terminal (with full symlink path)
> 
>     3. reboot
> 
> 
> I do not have a better workaround right now. This is the limitation caused by starting this as part of `gnome-shell` process. If this is still problematic, I will **try** to find some way to get this working without workarounds...

I also forgot to link node! It works now. Thanks for taking the time to help!

**Comment by Markkop** [comment]
Cool! This worked for me:
```bash
sudo ln -s $(which npm) /usr/bin/
```
